# Site settings
title: garybuckle - health and fitness
email: iambuckle@icloud.com
author: Gary Buckle
description: All about staying fiot and healthy and being...happy!
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css


# Social icons
show_social_icons: true
github_username: garybuckle

# plugins
plugins: [jekyll-paginate]
paginate: 3
